from PyInquirer import prompt

ROLE_PRIMARY_DOMAIN_CONTROLLER = 'Primary DC'
ROLE_SECONDARY_DOMAIN_CONTROLLER = 'Secondary DC'
ROLE_EXCHANGE = 'Exchange'
ROLE_WEB_SERVER = 'Web Server'
ROLE_AD_FOREST = 'AD Forest'
ROLE_WORKSTATION = 'Workstation'



AVAILABLE_ROLES = [ROLE_PRIMARY_DOMAIN_CONTROLLER, ROLE_SECONDARY_DOMAIN_CONTROLLER, ROLE_WEB_SERVER, ROLE_EXCHANGE, ROLE_AD_FOREST, ROLE_WORKSTATION]


def roles_from_extracted_info(roles):
    return []